### ISSUE TITLE
Inventory Management

### ISSUE THREAD

**Issue by seoester** [KillingSpark/HaDiBar#17]
Existing inventory cannot be managed within HaDiBar, i.e. there is no way of explicitly (manually) changing the number of items in stock. This is very impractical, as a new "kind of beverage" has to be created every time there is a stock-up. Analogously, irregular removal of stock cannot be represented within HaDiBar.

**Comment by KillingSpark** [comment]
This is implemented in the webapp-repo and the new version is pulled in at 9ea05380c75e2512bfb469eb456306d5ab01e733
